export { getExternalIdQuery } from './getExternalId.query'
export { getWorkspaceCfTemplateQuery } from './getWorkspaceCfTemplate.query'
export { getWorkspaceCfUrlQuery } from './getWorkspaceCfUrl.query'
export { getWorkspaceCloudAccountsQuery } from './getWorkspaceCloudAccounts.query'
export { getWorkspaceReportSummaryQuery } from './getWorkspaceReportSummary.query'
