export const panelUI = {
  drawerWidth: 240,
  drawerWidthMobile: 57,
  drawerWidthClosed: 65,
  headerHeight: 64,
  bottomCopyRightHeight: 39,
  tablePaginationHeight: 52,
  maxPageModalWidth: 1440,
  snackbarAutoHideDuration: 3000,
  inputChangeDebounce: 1000,
  fastInputChangeDebounce: 300,
  tableViewMinHeight: 500,
  inventoryTableCellMinWidth: 200,
  offsetHeightToLoad: 300,
}
