name: 'PR Checks'
on: [pull_request]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install
        run: yarn install
      
      - name: Add models
        run: |
          echo "[]" > mock-apis/data/model.json
          echo "{ \"accounts\": [], \"regions\": [], \"kinds\": [], \"severity\": [] }" > mock-apis/data/search-start.json
          echo "[]" > mock-apis/data/table.json
          echo "[]" > mock-apis/data/tags.json

      - name: Run tests
        run: yarn test

      - name: Run Lint
        run: yarn lint

      - name: Run Lint TSC
        run: yarn lint:tsc

      - name: Run check prettier
        run: yarn format:check

      - name: Run Test Build
        run: yarn build

      - name: Run Test Storybook Build
        run: yarn build-storybook

      - name: Publish Test Build
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.FIX_UI_DO_SPACES_KEY }}
          secret_key: ${{ secrets.FIX_UI_DO_SPACES_SECRET }}
          space_name: ${{ secrets.FIX_UI_DO_SPACE_NAME }}
          space_region: ${{ secrets.FIX_UI_DO_SPACE_REGION }}
          out_dir: fix-test-ui-build/${{github.event.number}}
          source: dist
