name: 'publish' 
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: ./build-ci.sh

      - name: Publish to CDN 
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.FIX_UI_DO_SPACES_KEY }}
          secret_key: ${{ secrets.FIX_UI_DO_SPACES_SECRET }}
          space_name: ${{ secrets.FIX_UI_DO_SPACE_NAME }}
          space_region: ${{ secrets.FIX_UI_DO_SPACE_REGION }}
          out_dir: fix-ui
          source: target

      - name: Create a conigmap with the version
        # writes the file with a config map definition
        run: |
          echo "apiVersion: v1" > configmap.yaml
          echo "kind: ConfigMap" >> configmap.yaml
          echo "metadata:" >> configmap.yaml
          echo "  name: fix-ui" >> configmap.yaml
          echo "data:" >> configmap.yaml
          echo "  version: ${{ github.sha }}" >> configmap.yaml

      - name: Authenticate with GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.SOME_CI_PAT }}"

      - name: Bump fix-ui version
        env:
          GITHUB_TOKEN: ${{ secrets.SOME_CI_PAT }}
        run: |
          git config --global user.email "ci@some.engineering"
          git config --global user.name "Some CI"
          git clone "https://$GITHUB_TOKEN@github.com/someengineering/setup-infra.git"
          # update the configmap
          mv configmap.yaml setup-infra/argocd/envs/dev/fixbackend/fixbackend-ui-version.yaml
          git add .
          git commit -m "Bump fix-ui to ${{ github.sha }}" 
          git push origin main